dice_lounge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler403, handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'dice_lounge.views.custom_error_403'
handler404 = 'dice_lounge.views.custom_error_404'
handler500 = 'dice_lounge.views.custom_error_500'

home/urls.py
"""
dice_lounge URL Configuration
Home app
"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

products/urls.py
"""
dice_lounge URL Configuration
Products app
"""
from django.urls import path
from . import views

urlpatterns = [
     path('', views.all_games, name='all_games'),
     path('search_results/', views.search_results, name='search_results'),
     path(
          '<int:product_line_id>/',
          views.products,
          name='products'
     ),
     path(
          'detail/<int:product_id>/',
          views.product_detail,
          name='product_detail'
     ),
     path(
          'get_lookup/<lookup_type>/',
          views.get_lookup,
          name='get_lookup'
     ),
     path(
          'product_management/',
          views.product_management,
          name='product_management'),
     path(
          'add/<request_config_key>/',
          views.add,
          name='add'
     ),
     path(
          'edit/<request_config_key>/<int:object_id>/',
          views.edit,
          name='edit'
     )
]

checkout/models.py
# ...................................................Modified Boutique-Ado Code
import uuid
from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from profiles.models import UserProfile


# Create your models here.
class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='orders'
    )
    first_name = models.CharField(max_length=25, null=False, blank=False)
    last_name = models.CharField(max_length=25, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    postcode = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(
        blank_label='Country *',
        null=False,
        blank=False,
        default=settings.DEFAULT_COUNTRY
    )
    delivery_first_name = models.CharField(
        max_length=25, null=False, blank=False)
    delivery_last_name = models.CharField(
        max_length=25, null=False, blank=False)
    delivery_address1 = models.CharField(
        max_length=80, null=False, blank=False)
    delivery_address2 = models.CharField(max_length=80, null=True, blank=True)
    delivery_town_or_city = models.CharField(
        max_length=40, null=False, blank=False)
    delivery_county = models.CharField(max_length=80, null=True, blank=True)
    delivery_postcode = models.CharField(
        max_length=20, null=False, blank=False)
    delivery_country = CountryField(
        blank_label='Country *',
        null=False,
        blank=False,
        default=settings.DEFAULT_COUNTRY
    )
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_basket = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
            Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
            update grand total each time a line item is added, accounting for
            delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = (
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
            )
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
            Override the original save method to set the order number if it
            hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()

        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='lineitems'
    )
    product_id = models.IntegerField(
        null=True, blank=False, default=-1)
    product = models.CharField(
        max_length=254, blank=False, null=False)
    sub_product_line = models.CharField(
        max_length=254, blank=False, null=False)
    product_line = models.CharField(
        max_length=254, blank=False, null=False)
    quantity = models.IntegerField(
        null=False, blank=False, default=0)
    item_price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        blank=False,
        default=0.00
    )
    lineitem_total = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        blank=False,
        default=0.00
    )

    def save(self, *args, **kwargs):
        """
            Override the original save method to set the lineitem total.
        """
        self.lineitem_total = self.item_price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'ID {self.product_id} on order {self.order.order_number}'
# ...............................................End Modified Boutique-Ado Code

products/models.py
from django.core.exceptions import ValidationError
from django.core.validators import (
    DecimalValidator, MinValueValidator, MaxValueValidator)
from django.db import models
from django.shortcuts import get_object_or_404
from django.conf import settings
from decimal import Decimal


# Custom Validators here.
# Prevent whitespace from being included in a field
def validate_whitespace(value):
    if " " in value:
        raise ValidationError('No Spaces Allowed')
    else:
        return value


# Create your models here.
# Product Line images written to:
#   <media root>/covers/<publisher.identifier>/
def product_line_image_path(instance, filename):
    return f'covers/{instance.publisher.identifier}/{filename}'


# Sub Product Line images written to:
#   <media root>/<product_line.identifier>/
def sub_product_line_image_path(instance, filename):
    return f'{instance.product_line.identifier}/{filename}'


# Product images written to:
#   <media root>/<product_line.identifier>/<sub_product_line.identifier>
def product_image_path(instance, filename):
    return (f'{instance.sub_product_line.product_line.identifier}/' +
            f'{instance.sub_product_line.identifier}/{filename}')


class Category(models.Model):
    class Meta:
        verbose_name_plural = "Categories"

    identifier = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        validators=[validate_whitespace],
        verbose_name='Category Identifier',
        help_text='Please use underscores instead of spaces.  Must be unique.'
    )
    name = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        verbose_name='Category',
        help_text='Please enter a descriptive name for this Category.  \
            Must be unique.'
    )

    def __str__(self):
        return self.name

    def get_id(self):
        return self.identifier

    def clean(self):
        self.identifier = self.identifier.lower()


class Genre(models.Model):
    identifier = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        validators=[validate_whitespace],
        verbose_name='Genre Identifier',
        help_text='Please use underscores instead of spaces.  Must be unique.'
    )
    name = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        verbose_name='Genre',
        help_text='Please enter a descriptive name for this Genre.  \
            Must be unique.'
    )

    def __str__(self):
        return self.name

    def get_id(self):
        return self.identifier

    def clean(self):
        self.identifier = self.identifier.lower()


class Publisher(models.Model):
    identifier = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        validators=[validate_whitespace],
        verbose_name='Publisher Identifier',
        help_text='Please use underscores instead of spaces.  Must be unique.'
    )
    name = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        verbose_name='Publisher',
        help_text='Please enter a descriptive name for this Publisher.  \
            Must be unique.'
    )

    def __str__(self):
        return self.name

    def get_id(self):
        return self.identifier

    def clean(self):
        self.identifier = self.identifier.lower()


class Stock_State(models.Model):
    class Meta:
        verbose_name = "Stock State"

    identifier = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        validators=[validate_whitespace],
        verbose_name='Stock State Identifier',
        help_text='Please use underscores instead of spaces.  Must be unique.'
    )
    state = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        verbose_name='Stock State',
        help_text='Please enter a descriptive name for this Stock State.  \
            Must be unique.'
    )
    available = models.BooleanField(
        blank=False,
        null=False,
        default=False,
        verbose_name='Available to Order?',
        help_text='Does this Stock State indicate that items are available ' +
        'to order?'
    )

    def __str__(self):
        return self.state

    def get_id(self):
        return self.identifier

    def clean(self):
        self.identifier = self.identifier.lower()


class Reduced_Reason(models.Model):
    class Meta:
        verbose_name = "Reduced Price Reason"

    identifier = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        validators=[validate_whitespace],
        verbose_name='Reduced Price Reason Identifier',
        help_text='Please use underscores instead of spaces.  Must be unique.'
    )
    reason = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        verbose_name='Reduced Price Reason',
        help_text=(
            'Please enter a descriptive name for this Reduced Price Reason.  \
                Must be unique.'
        )
    )
    default_reduction_percentage = models.IntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(settings.MAX_PERCENTAGE_REDUCTION)
        ],
        null=False,
        blank=False,
        default=settings.DEFAULT_PERCENTAGE_REDUCTION,
        verbose_name='Default Price Reduction Percentage',
        help_text='Please enter a default reduction % for this ' +
        f'reason (0-{settings.MAX_PERCENTAGE_REDUCTION}).'
    )

    def __str__(self):
        return self.reason

    def get_id(self):
        return self.identifier

    def clean(self):
        self.identifier = self.identifier.lower()


class Product_Line(models.Model):
    class Meta:
        verbose_name = "Product Line"

    identifier = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        validators=[validate_whitespace],
        verbose_name='Product Line Identifier',
        help_text='Please use underscores instead of spaces.  Must be unique.'
    )
    name = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        verbose_name='Product Line',
        help_text=(
            'Please enter a descriptive name for this Product Line.  \
                Must be unique.'
        )
    )
    category = models.ForeignKey(
        'Category',
        null=False,
        blank=False,
        on_delete=models.RESTRICT,
        help_text='Please select a category for this Product Line.'
    )
    genre = models.ForeignKey(
        'Genre',
        null=False,
        blank=False,
        on_delete=models.RESTRICT,
        help_text='Please select a genre for this Product Line.'
    )
    publisher = models.ForeignKey(
        'Publisher',
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        help_text='Please select a publisher for this Product Line.'
    )
    description = models.TextField(
        max_length=500,
        blank=True,
        null=True,
        help_text='Please enter a description for this Product Line.'
    )
    image = models.ImageField(
        null=True,
        blank=True,
        max_length=2000,
        upload_to=product_line_image_path,
        help_text=(
            '(Optional) Please add an image for this Product Line.'
        )
    )
    hidden = models.BooleanField(
        null=False,
        blank=False,
        default=False,
        help_text='Hide this Product Line (and all child Sub Product Lines and \
            Products) from view?'
    )

    def __str__(self):
        return self.name

    def get_id(self):
        return self.identifier

    def is_hidden(self):
        return self.hidden

    def clean(self):
        self.identifier = self.identifier.lower()


class Sub_Product_Line(models.Model):
    class Meta:
        verbose_name = "Sub Product Line"

    product_line = models.ForeignKey(
        'Product_Line',
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        help_text='Please assign this Sub Product Line to a Product Line'
    )
    identifier = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        unique=True,
        validators=[validate_whitespace],
        verbose_name='Sub Product Line Identifier',
        help_text='Please use underscores instead of spaces.  Must be unique.'
    )
    name = models.CharField(
        max_length=254,
        blank=False,
        null=False,
        verbose_name='Sub Product Line',
        help_text=(
            'Please enter a descriptive name for this Sub Product Line.'
        )
    )
    description = models.TextField(
        max_length=500,
        blank=True,
        null=True,
        help_text='Please enter a description for this Sub Product Line'
    )
    core_set = models.BooleanField(
        null=False,
        blank=False,
        default=False,
        help_text='Does this Sub Product Line contain Core Sets/Rules?'
    )
    scenics = models.BooleanField(
        null=False,
        blank=False,
        default=False,
        help_text='Does this Sub Product Line contain Scenics and/or Terrain?'
    )
    image = models.ImageField(
        null=True,
        blank=True,
        max_length=2000,
        upload_to=sub_product_line_image_path,
        help_text=(
            '(Optional) Please add an image for this Sub Product Line.'
        )
    )
    hidden = models.BooleanField(
        null=False,
        blank=False,
        default=False,
        help_text='Hide this Sub Product Line (and all child Products) from \
            view?'
    )

    def __str__(self):

products/templates/products/category_admin.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
    <link rel="stylesheet" href="{% static 'products/css/products.css' %}">
{% endblock extra_css %}

{% block page_header %}
    <div class="header-spacer"></div>
{% endblock page_header %}

{% block content %}
    <div class="h-100 w-100 bg-light position-fixed top-0 left-0 z-index-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6 offset-lg-3">
                <h2 class="logo-font mt-3 mb-4 text-center">Product Management</h2>
                <h5 class="text-muted text-center">{% if view == 'add_category' %}Add a Category{% elif view == 'edit_category' %}Edit Category{% endif %}</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-6 offset-lg-3">
                <form method="POST" id="categoryAdminForm" action="{% if view == 'add_category' %}{% url 'add' 'category' %}{% else %}{% url 'edit' 'category' category_id %}{% endif %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Identifier -->
                    {{ category_form.identifier | as_crispy_field }}
                    <!-- Name -->
                    {{ category_form.name | as_crispy_field }}
                    <hr>
                    <div class="row position-sticky btt-row pe-none mb-1">
                        <div class="col-12 text-end">
                            {% include "includes/btt_button.html" %}
                        </div>
                    </div>
                    <div class="text-end">
                        <a class="btn btn-outline-dark text-dark hover-background-red" href="{% url 'product_management' %}">Cancel</a>
                        <button class="btn btn-dark text-light hover-background-red" type="submit">{% if view == 'add_product' %}Add Sub Product Line{% else %}Save Changes{% endif %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block postload_js %}
    {{ block.super }}
    <script src="{% static 'products/js/admin_dropdown.js' %}"></script>
    <script src="{% static 'products/js/admin_input_masks.js' %}"></script>
    <script src="{% static 'products/js/admin.js' %}"></script>
{% endblock postload_js %}

products/templates/products/product_line_admin.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
    <link rel="stylesheet" href="{% static 'products/css/products.css' %}">
{% endblock extra_css %}

{% block page_header %}
    <div class="header-spacer"></div>
{% endblock page_header %}

{% block content %}
    <div class="h-100 w-100 bg-light position-fixed top-0 left-0 z-index-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6 offset-lg-3">
                <h2 class="logo-font mt-3 mb-4 text-center">Product Management</h2>
                <h5 class="text-muted text-center">{% if view == 'add_product_line' %}Add a Product Line{% else %}Edit Product Line{% endif %}</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-6 offset-lg-3">
                <form method="POST" id="productLineAdminForm" action="{% if view == 'add_product_line' %}{% url 'add' 'product_line' %}{% else %}{% url 'edit' 'product_line' product_line_id %}{% endif %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Identifier -->
                    {{ product_line_form.identifier | as_crispy_field }}
                    <!-- Name -->
                    {{ product_line_form.name | as_crispy_field }}
                    <!-- Category -->
                    <div class="dropdown-wrapper admin-dropdown d-block w-100 mb-3">
                        <div class="dropdown position-relative border border-1 border-dark">
                            <input type="hidden" name="category" value="{{ product_line_form.category.value }}" id="id_category" data-isvalid="true">
                            <a class="text-dark dropdown-toggle text-decoration-none" href="#" id="categoryToggler" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                            <div class="dropdown-menu bg-light text-dark shadow-lg border border-1 border-dark" aria-labelledby="categoryToggler">
                                <div class="dropdown-items-container"></div>
                            </div>
                        </div>
                        <div class="mb-3 text-danger dropdown-error-message d-none" id="categoryErrors" role="alert"></div>
                        <small id="hint_id_category" class="form-text text-muted dropdown-help-text">{{ product_line_form.category.help_text }}</small>
                    </div>
                    <!-- Genre -->
                    <div class="dropdown-wrapper admin-dropdown d-block w-100 mb-3">
                        <div class="dropdown position-relative border border-1 border-dark">
                            <input type="hidden" name="genre" value="{{ product_line_form.genre.value }}" id="id_genre" data-isvalid="true">
                            <a class="text-dark dropdown-toggle text-decoration-none" href="#" id="genreToggler" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                            <div class="dropdown-menu bg-light text-dark shadow-lg border border-1 border-dark" aria-labelledby="genreToggler">
                                <div class="dropdown-items-container"></div>
                            </div>
                        </div>
                        <div class="mb-3 text-danger dropdown-error-message d-none" id="genreErrors" role="alert"></div>
                        <small id="hint_id_genre" class="form-text text-muted dropdown-help-text">{{ product_line_form.genre.help_text }}</small>
                    </div>
                    <!-- Publisher -->
                    <div class="dropdown-wrapper admin-dropdown d-block w-100 mb-3">
                        <div class="dropdown position-relative border border-1 border-dark">
                            <input type="hidden" name="publisher" value="{{ product_line_form.publisher.value }}" id="id_publisher" data-isvalid="true">
                            <a class="text-dark dropdown-toggle text-decoration-none" href="#" id="publisherToggler" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                            <div class="dropdown-menu bg-light text-dark shadow-lg border border-1 border-dark" aria-labelledby="publisherToggler">
                                <div class="dropdown-items-container"></div>
                            </div>
                        </div>
                        <div class="mb-3 text-danger dropdown-error-message d-none" id="publisherErrors" role="alert"></div>
                        <small id="hint_id_publisher" class="form-text text-muted dropdown-help-text">{{ product_line_form.publisher.help_text }}</small>
                    </div>
                    <!-- Description -->
                    {{ product_line_form.description | as_crispy_field }}
                    <!-- Image -->
                    {{ product_line_form.image }}
                    <!-- Hidden -->
                    {{ product_line_form.hidden | as_crispy_field }}
                    <hr>
                    <div class="row position-sticky btt-row pe-none mb-1">
                        <div class="col-12 text-end">
                            {% include "includes/btt_button.html" %}
                        </div>
                    </div>
                    <div class="text-end">
                        <a class="btn btn-outline-dark text-dark hover-background-red" href="{% url 'product_management' %}">Cancel</a>
                        <button class="btn btn-dark text-light hover-background-red" type="submit">{% if view == 'add_product' %}Add Product Line{% else %}Save Changes{% endif %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block postload_js %}
    {{ block.super }}
    <script src="{% static 'products/js/admin_dropdown.js' %}"></script>
    <script src="{% static 'products/js/admin_input_masks.js' %}"></script>
    <script src="{% static 'products/js/admin.js' %}"></script>
{% endblock postload_js %}

products/templates/products/sub_product_line_admin.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
    <link rel="stylesheet" href="{% static 'products/css/products.css' %}">
{% endblock extra_css %}

{% block page_header %}
    <div class="header-spacer"></div>
{% endblock page_header %}

{% block content %}
    <div class="h-100 w-100 bg-light position-fixed top-0 left-0 z-index-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6 offset-lg-3">
                <h2 class="logo-font mt-3 mb-4 text-center">Product Management</h2>
                <h5 class="text-muted text-center">{% if view == 'add_product_line' %}Add a Sub Product Line{% else %}Edit Sub Product Line{% endif %}</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-6 offset-lg-3">
                <form method="POST" id="subProductLineAdminForm" action="{% if view == 'add_sub_product_line' %}{% url 'add' 'sub_product_line' %}{% else %}{% url 'edit' 'sub_product_line' sub_product_line_id %}{% endif %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Product Line -->
                    <div class="dropdown-wrapper admin-dropdown d-block w-100 mb-3">
                        <div class="dropdown position-relative border border-1 border-dark">
                            <input type="hidden" name="product_line" value="{{ sub_product_line_form.product_line.value }}" id="id_product_line" data-isvalid="true">
                            <a class="text-dark dropdown-toggle text-decoration-none" href="#" id="productLineToggler" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                            <div class="dropdown-menu bg-light text-dark shadow-lg border border-1 border-dark" aria-labelledby="productLineToggler">
                                <div class="dropdown-items-container"></div>
                            </div>
                        </div>
                        <div class="mb-3 text-danger dropdown-error-message d-none" id="productLineErrors" role="alert"></div>
                        <small id="hint_id_product_line" class="form-text text-muted dropdown-help-text">{{ sub_product_line_form.product_line.help_text }}</small>
                    </div>
                    <!-- Identifier -->
                    {{ sub_product_line_form.identifier | as_crispy_field }}
                    <!-- Name -->
                    {{ sub_product_line_form.name | as_crispy_field }}
                    <!-- Description -->
                    {{ sub_product_line_form.description | as_crispy_field }}
                    <!-- Core_Set -->
                    {{ sub_product_line_form.core_set | as_crispy_field }}
                    <!-- Scenics -->
                    {{ sub_product_line_form.scenics | as_crispy_field }}
                    <!-- Image -->
                    {{ sub_product_line_form.image }}
                    <!-- Hidden -->
                    {{ sub_product_line_form.hidden | as_crispy_field }}
                    <hr>
                    <div class="row position-sticky btt-row pe-none mb-1">
                        <div class="col-12 text-end">
                            {% include "includes/btt_button.html" %}
                        </div>
                    </div>
                    <div class="text-end">
                        <a class="btn btn-outline-dark text-dark hover-background-red" href="{% url 'product_management' %}">Cancel</a>
                        <button class="btn btn-dark text-light hover-background-red" type="submit">{% if view == 'add_product' %}Add Sub Product Line{% else %}Save Changes{% endif %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block postload_js %}
    {{ block.super }}
    <script src="{% static 'products/js/admin_dropdown.js' %}"></script>
    <script src="{% static 'products/js/admin_input_masks.js' %}"></script>
    <script src="{% static 'products/js/admin.js' %}"></script>
{% endblock postload_js %}